### ISSUE TITLE
[Testing Session] Feedback 

### ISSUE THREAD

**Issue by GAON25** [swsnu/swppfall2022-team19#83]
swppfall2022-team19
LetmeCU

**Comment by engineerA314** [comment]
회원가입 시에 입력한 즐겨찾기 카테고리가, 회원 정보 수정에 들어가면 비어 있었습니다. 회원가입 시에 입력한 정보가 반영되지 않는 것 같습니다.

**Comment by gkgkgkgkgk73** [comment]
상품 후기 위쪽에 깨진 부분이 있습니다.
사용자 정보 수정 칸이 깨져 있습니다.
디자인이 깔끔하고 마우스를 올리면 이미지 커지는 것이 좋습니다.

**Comment by lukaspark16** [comment]
상품 후기 위쪽에 깨진 부분이 있고 사용자 정보 수정 칸이 깨져있어요! 수고하셨습니다 👍

**Comment by Whiteppanda** [comment]
디자인이 이뻐요
데이터가 더 많았으면 좋겠어요.
홈 화면의 플리커? 제대로 작동했으면 좋겠어요
회원가입 시에 입력한 즐겨찾기 카테고리가 처음에 반영이 안되어있어요

**Comment by askrid** [comment]
리뷰 개수나 별점 등으로 정렬이 가능하면 좋을 것 같습니다.

**Comment by ImPJH** [comment]
리뷰에서 파이 그래프가 점수에 따라 색깔이 바뀌는 데 이를 설명하는 부분의 UI가 깨져 있었습니다.

**Comment by ozeeeno** [comment]
1. 디자인이 좋습니다.
2. 신제품에 대해서만 등록되어 있어서 알고 있던 제품을 검색하면 안 나온다는 점이 아쉽습니다. 
3. 리뷰와 통계가 실시간으로 반영되는 것이 좋은 것 같습니다.

**Comment by jhm1313** [comment]
1. 메인 화면에 아이템 4개 랜덤으로 바뀌는거 재밌는데, 셔플해주는 버튼 아예 만들어주실 수 있나요?
2. 가격 순이나, 리뷰 평점 순, 혹은 리뷰 개수 순 등으로 정렬하는 기능이 있으면 좋을 것 같습니다.
3. 리뷰에서 사진 보기를 눌렀을 때 사진을 너무 왼쪽으로 정렬하지 않고 가운데 정렬 + 따로 프레임을 만들어주시면 좋을 것 같습니다.
4. 아이템 위에 마우스를 오버했을 때 상품 이미지의 크기가 커지는 것이 좋았습니다. 추가로 배경 색도 약간 어두워지면 더 좋을 것 같습니다.

**Comment by taeminers** [comment]
미드프레젠테이션 이후로 정말 많이 발전하신 것 같습니다. 고생하셨습니다.
마이페이지 UI 아랫부분이 조금 혼잡해 보여서 그 부분만 수정하시면 정말 좋을 것 같습니다.

**Comment by Young-in** [comment]
너무 예쁘게 잘 만드셨어요.

리뷰를 작성한 결과가 바로 보일 수 있게 해당 리뷰로 스크롤이 된다거나 리뷰 위치가 조금 바뀌었으면 좋겠어요.

검색을 카테고리 이름(ex. 아이스크림 등)으로 검색할 수도 있으면 좋을 것 같습니다.

**Comment by diffzerg** [comment]
UI가 깔끔하고 DB도 다양하게 추가 많이 해주셔서 테스트하는 재미가 있었습니다.
state check 후 redirect하는 부분들 다시 확인해보시면 좋을 것 같습니다 (http 사이트 접속시 로그인하지 않았음에도 로그아웃 버튼이 활성화되어 있었음)

**Comment by insung151** [comment]
프로젝트 완성도가 뛰어난거 같습니다!
검색키워드를 입력하고 엔터키를 눌러도 검색이 되도록 구현해주시면 사용할 때 좀 더 편할거 같습니다.

**Comment by vietman2** [comment]
- "전체" 탭이 있었으면 좋을것 같습니다
- 상품명에 띄어쓰기가 적용되면 좋을 것 같습니다
- 검색이나 필터기능 더 보완할 수 있을 것 같습니다 (예를 들어 카테고리로 검색하거나, 상품에 태그를 추가하는 등)
- 전반적으로 디자인도 예쁘고 완성도도 높은 것 같습니다

**Comment by jaeyoungleeee** [comment]
가장 많이 받은 추천이 바로 바뀌는 것에 놀랐습니다!
잘 구현해주신 것 같습니다!

**Comment by keetae423** [comment]
- 검색 시 엔터 버튼 눌러도 검색이 되게끔 해주시면 좋을 것 같습니다.

- 전반적인 완성도가 다른 팀들에 비해 높았습니다. 아이템에 mouse hover 시 이미지 살짝 확대해 보여주시는 등 디테일 부분까지 완성이 되어있다고 느껴졌습니다. 

- 미평가 제품에 대해서는 평점을 0점을 아니라 미평가 제품이라고 따로 표기해주시면 좋을 것 같습니다.

- 중복된 ID가 아닐 것 같은데 중복된 ID라는 alert message가 떴는데 확인해주시면 좋을 것 같습니다
![image](https://user-images.githubusercontent.com/55076957/206166054-6dd9e1b8-6d22-470c-a728-fb9a27bcfae1.png)

**Comment by Quantee-OH** [comment]
Feedback(team20)
UI가 되게 귀엽고 맘에 듭니다!
(버그)검색창에 ".."로 검색하는 경우 홈화면으로 리다이렉팅 되는 것 같습니다.
